---
- name: yay | Create user for yay
  user:
    name: 'aur_builder'
    home: '/home/.aur_builder'

- name: yay | Allow passwordless pacman for aur_builder
  blockinfile:
    path: /etc/sudoers
    marker: '# {mark} Ansible managed: yay role'
    create: yes
    block: |
      aur_builder ALL=(ALL) NOPASSWD:/bin/pacman

- name: yay | Add alias
  blockinfile:
    marker: '# {mark} Ansible managed: yay role'
    path: "{{ user.home }}/.zshrc_extra"
    block: |
      yay -S --noconfirm $1

- include_role: name='software'
