---
- name: Set timezone and hwclock
  timezone:
    name: "{{ timezone }}"
    hwclock: UTC

- name: Enable and start NTP synchronisation
  systemd:
    name: systemd-timesyncd.service
    enabled: True
    state: started
