---
- include_role: name='software'

- name: firefox | Create Downloads direcory
  file:
    state: directory
    path: '{{ user.home }}/Downloads'
  become_user: '{{ user.name }}'

- name: firefox | Download hardneded config (relaxed version)
  get_url:
    url: https://raw.githubusercontent.com/pyllyukko/user.js/relaxed/user.js
    dest: '/tmp/'
  when: relaxed_version == True

- name: firefox | Download hardneded config (max sec)
  get_url:
    url: 'https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js'
    dest: '/tmp/'
  when: relaxed_version != True

- name: firefox | Comment unwanted options from hardened config
  script: 'comment_bad_options.py /tmp/user.js'

- name: firefox | Copy file with my custom options
  copy:
    src: 'my_options.cfg'
    dest: '/tmp/'

- name: firefox | Append my custom options to firefox config
  shell: 'cat /tmp/my_options.cfg >> /tmp/user.js'

- name: firefox | Place user.js
  command: 'cp /tmp/user.js {{ user.home }}/.mozilla/firefox/*.default-release/user.js'
