---
- include_role: name='software'

- name: firefox | Create Downloads direcory
  file:
    state: directory
    path: '{{ user.home }}/Downloads'

- name: firefox | Download hardneded config
  get_url:
    url: 'https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js'
    dest: '/tmp/'

- name: firefox | Comment unwanted options from hardened config
  script: 'comment_bad_options.py /tmp/user.js'

- name: firefox | Copy file with my custom options
  copy:
    src: 'my_options.cfg'
    dest: '/tmp/'

- name: firefox | Append my custom options to firefox config
  shell: 'cat /tmp/my_options.cfg >> /tmp/user.js'

- name: firefox | Delete previous user.js
  file:
    state: absent
    path: '{{ user.home }}/.mozilla/firefox/{{ firefox.profile }}/user.js'

- name: firefox | Place user.js
  copy:
    remote_src: yes
    src: '/tmp/user.js'
    dest: '{{ user.home }}/.mozilla/firefox/{{ firefox.profile }}/user.js'
    owner: '{{ user.name }}'
