---
- include_role: name='software'

- name: firefox | Download hardneded config (relaxed version)
  get_url:
    url: https://raw.githubusercontent.com/pyllyukko/user.js/relaxed/user.js
    dest: '/tmp/'
  when: relaxed_version == True
  changed_when: false

- name: firefox | Download hardneded config (max sec)
  get_url:
    url: 'https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js'
    dest: '/tmp/'
  when: relaxed_version != True
  changed_when: false

- name: firefox | Place script to /tmp
  copy:
    src: comment_bad_options.py
    dest: /tmp/
  changed_when: false

- name: firefox | Comment unwanted options from hardened config
  command: 'python3 /tmp/comment_bad_options.py /tmp/user.js'
  changed_when: false

- name: firefox | Copy file with my custom options
  copy:
    src: 'my_options.cfg'
    dest: '/tmp/'
  changed_when: false

- name: firefox | Append my custom options to firefox config
  shell: 'cat /tmp/my_options.cfg >> /tmp/user.js'
  changed_when: false

- name: firefox | Get profile folder name 1
  shell:  ls -d {{ user.home }}/.mozilla/firefox/*.default-release  | awk '{print $(NF)}'
#  shell: 'ls -d {{ user.home }}/.mozilla/firefox/*.default-release | grep default-release'
  register: ff_dir_name1
  changed_when: false

- name: firefox | Get profile folder name 2
  shell:  ls -d {{ user.home }}/.mozilla/firefox/*.default  | awk '{print $(NF)}' | grep -v release
  #shell: 'ls -d {{ user.home }}/.mozilla/firefox/*.default  | grep default | grep -v release'
  register: ff_dir_name2
  changed_when: false

- name: firefox | Place user.js to default and custom profile
  copy:
    remote_src: yes
    src: /tmp/user.js
    dest: '{{ item }}'
  with_items:
    - '{{ ff_dir_name1.stdout }}'
    - '{{ ff_dir_name2.stdout }}'
# TODO: if def:
#    - '/home/user1/.mozilla/firefox/{{ firefox.profile_dir}}'
  become_user: '{{ user.name }}'

- name: firefox | Create Downloads direcory
  file:
    state: directory
    path: '{{ user.home }}/Downloads'
  become_user: '{{ user.name }}'
