---
- block:
  - block:
    - name: firefox | Download hardneded config (relaxed version)
      get_url:
        url: https://raw.githubusercontent.com/pyllyukko/user.js/relaxed/user.js
        dest: '/tmp/'
      when: firefox_config == 'relaxed'
      changed_when: false
    
    - name: firefox | Download hardneded config (max sec)
      get_url:
        url: 'https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js'
        dest: '/tmp/'
      when: firefox_config == 'hardened'
      changed_when: false
    
    - name: firefox | Place script to /tmp
      copy:
        src: comment_bad_options.py
        dest: /tmp/
      changed_when: false
    
    - name: firefox | Comment unwanted options from hardened config
      command: 'python3 /tmp/comment_bad_options.py /tmp/user.js'
      changed_when: false
    when: firefox_config != ''
    
  - name: firefox | Copy file with my custom options
    copy:
      src: 'my_options.cfg'
      dest: '/tmp/'
    changed_when: false
  
  - name: firefox | Append my custom options to firefox config
    shell: 'cat /tmp/my_options.cfg >> /tmp/user.js'
    changed_when: false
  
  - name: firefox | Get profile folder name 1
    shell:  ls -d {{ user.home }}/.mozilla/firefox/*.default-release  | awk '{print $(NF)}'
    register: ff_dir_name1
    changed_when: false
    when:
    - ansible_os_family != "Debian" 

  - name: firefox | Get profile folder name 1
    shell:  ls -d {{ user.home }}/.mozilla/firefox/*.default-esr  | awk '{print $(NF)}'
    register: ff_dir_name1
    changed_when: false
    when:
    - ansible_os_family == "Debian" 
  
  - name: firefox | Get profile folder name 2
    shell:  ls -d {{ user.home }}/.mozilla/firefox/*.default  | awk '{print $(NF)}' | grep -v release
    register: ff_dir_name2
    changed_when: false
  
  - name: firefox | Place user.js to default and custom profile
    copy:
      remote_src: yes
      src: /tmp/user.js
      dest: '{{ item }}'
    with_items:
      - '{{ ff_dir_name1.stdout }}'
      - '{{ ff_dir_name2.stdout }}'
  # TODO: if def:
  #    - '/home/user1/.mozilla/firefox/{{ firefox.profile_dir}}'
  
  - name: firefox | Create Downloads direcory
    file:
      state: directory
      path: '{{ user.home }}/Downloads'

  become_user: '{{ user.name }}'
