packages:
  pacman:
    - 'telegram-desktop'
    - 'keepassxc'
    - 'qbittorrent'
    - 'libreoffice'
    - 'fbreader'
    - 'chromium'
    - 'torbrowser-launcher'
    - 'audacious'

  apt:
    - 'telegram-desktop'
    - 'keepassxc'
    - 'qbittorrent'
    - 'libreoffice'
    - 'fbreader'
    - 'chromium'

  pip:
    - 'youtube-dl'

  aur:
#    - 'etcher'
#    - 'woeusb'
#    - 'standardnotes-desktop'
    - 'grv'
