---
packages:
  common:
    - virtualbox
    - vagrant

  pacman:
    - virtualbox-guest-iso

  apt:
# TODO; needs to be installed manually?
    #- virtualbox-ext-pack
    - virtualbox-guest-additions-iso

  aur:
    - virtualbox-ext-oracle

