---
- block:
  - name: software | Make sure pip is installed if needed (debian-based)
    package: name=python3-pip
    when: 
      - packages.pip is defined
      - ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux" or ansible_facts['os_family'] == 'Ubuntu'

  - name: software | Make sure pip is installed if needed (arch)
    package: name=python-pip
    when: 
      - packages.pip is defined
      - ansible_os_family == "Archlinux"
#TODO: Will break in Centos8
#      or ansible_distribution == "CentOS"

  - name: software | Install common software
    package: name={{ item }}
    with_items: '{{ packages.common }}'
    when: packages.common is defined

  - name: software | Install software with pip (system-wide)
    pip: name={{ packages.pip_sys }}
    when: packages.pip_sys is defined

  - name: software | Install software with pip (for user only)
    pip:
        name: '{{ packages.pip }}'
        extra_args: --user
    when: packages.pip is defined
    become_user: '{{ user.name }}'
  
  - name: software | Install software with pacman
    package: name={{ item }}
    with_items: '{{ packages.pacman }}'
    when: 
      - ansible_os_family == "Archlinux"
      - packages.pacman is defined
  
  - name: software | Install software from AUR
    aur: name={{ item }}
    with_items: '{{ packages.aur }}'
    become_user: 'aur_builder'
    when: 
      - ansible_os_family == "Archlinux"
      - packages.aur is defined
      - user.name != "root"
  
  - name: software | Install software with apt
    package: name={{ item }}
    with_items: '{{ packages.apt }}'
    when: 
      - ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux" or ansible_facts['os_family'] == 'Ubuntu'
      - packages.apt is defined
  tags: 'software'
