---
- block:
  - name: min_software | Enable ripgrep repo
    yum_repository:
      name: ripgrep
      baseurl: 'https://download.copr.fedorainfracloud.org/results/carlwgeorge/ripgrep/epel-7-$basearch/'
      description: 'Repo for ripgrep install'
      #skip_if_unavailable: yes
      gpgcheck: yes
      gpgkey: 'https://download.copr.fedorainfracloud.org/results/carlwgeorge/ripgrep/pubkey.gpg'
      repo_gpgcheck: no  
  
  - name: min_software | Install carg (for fd)
    package:
      name: 'cargo'
  
  - name: min_software | Install fd 
    command: 'cargo install fd-find'

  - name: min_software | Add cargo dir to PATH
    blockinfile:
      marker: '# {mark} Ansible managed: min_software role, 1'
      path: "{{ user.home }}/.zshrc"
      block: |
        export PATH="{{ user.home }}/.cargo/bin:$PATH"

  - name: min_software | Download fzf git repo
    git:
      repo: 'https://github.com/junegunn/fzf.git'
      dest: '{{user.home}}/.fzf'

  - name: min_software | Install fzf
    command: '{{ user.home }}/.fzf/install --key-bindings --completion --update-rc'

  when:
    - ansible_facts['os_family'] == 'RedHat'

- name: min_software | Add fd alias for Debian-based
  blockinfile:
    marker: '# {mark} Ansible managed: min_software role, 2'
    path: "{{ user.home }}/.zshrc"
    block: |
      alias fd='fdfind'
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'

- include_role: name='software'
