---
- include_role: name='software'

- block:
    - name: i3blocks | Create directories
      file:
        state: directory
        path: '{{ item }}'
      with_items: 
        - '{{ user.home }}/.config/i3blocks'
        - '{{ user.home }}/.config/i3blocks/blocks'

    - name: i3blocks | Create i3blocks config
      copy:
        src: i3blocks_config
        dest: '{{ user.home }}/.config/i3blocks/config'

    - name: i3blocks | Create i3blocks config
      copy:
        src: music_player.sh
        dest: '{{ user.home }}/.config/i3blocks/music_player.sh'
        mode: 0700

    - name: i3blocks | Download volume module
      get_url:
        url: 'https://raw.githubusercontent.com/vivien/i3blocks-contrib/master/volume/volume'
        dest: '{{ user.home }}/.config/i3blocks/blocks/volume'
        mode: 'u+x'

  become_user: '{{ user.name }}'
