---
- include_role: name='software'

- name: pacman | Sort mirrors by reflector
  shell: reflector --latest 10 -p https --sort rate --save /etc/pacman.d/mirrorlist

- name: pacman | Add alias pacman = sudo pacman
  blockinfile:
    marker: '# {mark} Ansible managed: pacman role'
    path: "{{ user.home }}/.zshrc_extra"
    block: |
      alias pacman='sudo pacman'
  become_user: '{{ user.name }}'
