---
- include_role: name='software'

- name: tmux | Check if tmux is already installed
  stat:
    path: /usr/bin/tmux
  register: tmuxExecutable

- block: # Install in RedHat
  - name: tmux | Install dependencies
    package:
      name: '{{ item }}'
    with_items:
      - automake
      - libevent-devel
      - ncurses-devel
      - bison
      - byacc

  - name: tmux | Download tmux from git
    git:
      repo: https://github.com/tmux/tmux
      dest: '{{ user.home }}/.tmux_source'

  - name: tmux | Cofigure, make and place to /usr/bin
    shell: |
      cd {{ user.home }}/.tmux_source
      /bin/sh autogen.sh
      ./configure
      make
      cp tmux /usr/bin/tmux
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - tmuxExecutable.stat.exists == False

- block:
  - name: tmux | Create tmux config
    copy:
      src: tmux.conf
      dest: '{{ user.home }}/.tmux.conf'
  
  - name: tmux | Install tpm plguin manager
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: '{{ user.home }}/.tmux/plugins/tpm'
  become_user: '{{ user.name }}'
