---
- include_role: name='software'

- block:
  - name: docker | Add PGP key
    shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -  &&  apt-key fingerprint 0EBFCD88'
  
  - name: docker | Add repo
    shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
  
  - name: docker | Install docker in Debian-based system
    shell: 'apt-get update && apt-get install docker-ce docker-ce-cli containerd.io -y'
  when: ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux"

- name: docker | Enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: docker | Add user docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
