---
- include_role: name='software'
- include_role: name='cargo'

- block:
  - name: alacritty | Create config directory
    file:
      state: directory
      dest: '{{ user.home }}/.config/alacritty'
  
  - name: alacritty | Create config file
    copy:
      src: alacritty.yml
      dest: '{{ user.home }}/.config/alacritty/alacritty.yml'
  become_user: '{{ user.name }}'

- name: alacritty | Check that alacritty exists
  stat:
    path: '{{ user.home }}.local/bin/alacritty' 
  register: alacritty_bin
  when: 
    - ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu' #WHY NOT CENTOS?

- name: alacritty | Create desktop file
  file:
    src: 'Alacritty.desktop'
    dest: '/usr/share/applications/Alacritty.desktop'
  when: 
    - ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu' #WHY NOT CENTOS?

- name: alacritty | Install alacritty using cargo
  command: cargo install alacritty
  when: 
    - ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu' #WHY NOT CENTOS?
    - alacritty_bin.stat.exists == False 
  become_user: '{{ user.name }}'

# does not exists
#- name: alacritty | Create link
#  file:
#    state: link
#    src: '{{ user.home }}/.cargo/bin/alacritty'
#    dest: /usr/sbin/alacritty


#- block:
#  - name: 
#
#  when: os == debian
