---
- include_role: name='software'
- include_role: name='cargo'

- block:
  - name: alacritty | Create config directory
    file:
      state: directory
      dest: '{{ user.home }}/.config/alacritty'
  
  - name: alacritty | Create config file
    copy:
      src: alacritty.yml
      dest: '{{ user.home }}/.config/alacritty/alacritty.yml'
  become_user: '{{ user.name }}'

#TODO: create check that alacritty does not exist already

- name: alacritty | Install alacritty using cargo
  command: cargo install alacritty
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu' #WHY NOT CENTOS?
  become_user: '{{ user.name }}'

# does not exists
#- name: alacritty | Create link
#  file:
#    state: link
#    src: '{{ user.home }}/.cargo/bin/alacritty'
#    dest: /usr/sbin/alacritty


#- block:
#  - name: 
#
#  when: os == debian
