---
- name: Rock and roll!
  hosts: host1
  connection: ssh
  become: yes
  vars:
    #    ansible_python_interpreter: /usr/bin/python3
    user:
      name: 'root'
      home: '/root'
      #name: 'user1'
      #home: '/home/user1'
  roles:
    - { role: 'user',             tags: 'user' }
    - { role: 'zsh',              tags: 'zsh' }
    - { role: 'neovim',           tags: 'neovim' }
    - { role: 'tmux',             tags: 'tmux' }
    - { role: 'min_software',     tags: 'min_software' }
      
