---
- name: Rock and roll!
  hosts: localhost
  connection: local
  become: yes
  become_method: su
  vars:
    #root_access: False
    #user_access: False
    # TODO: sudo ???
    allow_sudo: False
    firefox_config: ''

    user:
      name: 'user'
      home: '/home/user'

  roles:
    - { role: 'user',                 tags: 'user' } # always 1st
    - { role: 'common_software',      tags: 'common' } # always 2nd
    - { role: 'extra_software',       tags: 'extra' }
    - { role: 'fonts',                tags: 'fonts' }
    - { role: 'zsh',                  tags: 'zsh' }
    - { role: 'nvim',                 tags: 'nvim' }
    - { role: 'tmux',                 tags: 'tmux' }
    - { role: 'thunar',               tags: 'thunar' }
    - { role: 'zathura',              tags: 'zathura' }
    - { role: 'typora',               tags: 'typora' }
    - { role: 'alacritty',            tags: 'alacritty' }
    - { role: 'firefox',              tags: 'firefox' }
#    - { role: 'mimes',                tags: 'mimes' }
