---
- name: Rock and roll!
  hosts: localhost
  connection: local
  become: yes
  become_method: su

  roles:
    - { role: 'user',                 tags: 'user' }
    - { role: 'common_software',      tags: 'common' }
    - { role: 'extra_software',       tags: 'extra' }
#    - { role: 'fonts',                tags: 'fonts' }
    - { role: 'zsh',                  tags: 'zsh' }
    - { role: 'nvim',                 tags: 'nvim' }
    - { role: 'tmux',                 tags: 'tmux' }
    - { role: 'thunar',               tags: 'thunar' }
    - { role: 'zathura',              tags: 'zathura' }
    - { role: 'typora',               tags: 'typora' }
    - { role: 'alacritty',            tags: 'alacritty','terminal' }
#    - { role: 'mimes',                tags: 'mimes' }
#    - { role: 'apparmor',             tags: 'apparmor' }
