---
- name: Rock and roll!
  hosts: localhost
  connection: local
  become: yes
  become_method: su

  roles:
    - { role: 'locale',               tags: 'locale' }
    - { role: 'time',                 tags: 'time' }
    - { role: 'user',                 tags: 'user' }
    - { role: 'yay',                  tags: 'yay' }
    - { role: 'pacman',               tags: 'pacman' }
    - { role: 'fstab',                tags: 'fstab' }
    - { role: 'extra_software',       tags: 'extra' }
    - { role: 'common_software',      tags: 'common' }
    - { role: 'fonts',                tags: 'fonts' }
    - { role: 'i3',                   tags: 'i3' }
    - { role: 'i3blocks',             tags: 'i3blocks' }
    - { role: 'zsh',                  tags: 'zsh' }
    - { role: 'nvim',                 tags: 'nvim' }
    - { role: 'tmux',                 tags: 'tmux' }
    - { role: 'thunar',               tags: 'thunar' }
    - { role: 'zathura',              tags: 'zathura' }
    - { role: 'alacritty',            tags: 'alacritty' }
    - { role: 'sound',                tags: 'sound' }
    - { role: 'docker',               tags: 'docker' }
    - { role: 'mimes'                 tags: 'mimes' }
      
  post_tasks:
    - name: Fix access rights for files in home dir
      shell: 'chmod -R go-rwx /home/{{ user.name }}/'
      tags: access

    - name: post | Show commands to finish configuration
      debug:
        msg: |
          #  EXECUTE THIS IN NVIM (load and activating plugins):
          #  call dein#install()
          #  CocInstall coc-clangd
          #  CocInstall coc-python
          #
          #  Start tmux and enter Ctrl+b then Sift+I (load plugins)

    - name: Show ascii art to get attention
      debug:
        msg: |
          #                   -`
          #                  .o+`
          #                 `ooo/
          #                `+oooo:
          #               `+oooooo:
          #               -+oooooo+:
          #             `/:-:++oooo+:
          #            `/++++/+++++++:
          #           `/++++++++++++++:
          #          `/+++ooooooooooooo/`
          #         ./ooosssso++osssssso+`
          #        .oossssso-````/ossssss+`
          #       -osssssso.      :ssssssso.
          #      :osssssss/        osssso+++.
          #     /ossssssss/        +ssssooo/-
          #   `/ossssso+/:-        -:/+osssso+-
          #  `+sso+:-`                 `.-/+oso:
          # `++:.                           `-/+/
          # .`                                 `
          #     MANUALLY ENTER COMMANDS ABOVE

# NOT READY:
#    - { role: 'dev-sec.os-hardening', tags: 'hardening' }
#    - { role: 'wifi-network',         tags: 'network' }
#    - { role: 'qemu',                 tags: 'qemu' }
#    - { role: 'speed_boost',          tags: 'speed_boost' }
#
# NOT USED:
# pyenv_zsh
      #    - { role: 'custom-hardening',     tags: 'hardening' }
      #    - { role: 'pihole',               tags: 'pihole' }
      #    - { role: 'iptables',             tags: 'iptables' }
#    - { role: 'mpd',                  tags: 'mpd' }
#    - { role: 'bluetooth',            tags: 'bluetooth' }
      #    - { role: 'wireguard',            tags: 'wireguard' }
