version: '3'

volumes:
  black_arch:

services:
  black_arch:
    build: ./
    container_name: black_arch
    network_mode: host
    privileged: true
    tty: true
    restart: unless-stopped 
    volumes:
      - /home/user0/hack:/root/hack
