version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres-kali
    ports:
      - 127.0.0.1:33333:5432
    env_file:
      - db.env
    volumes:
      - ~/.postgres_kali_db:/var/lib/postgresql/data

  kali:
    build: ./
    container_name: kali
    depends_on:
      - postgres-kali
    network_mode: "host"
    privileged: true
    hostname: kali
    command: tail -f /dev/null # keep container running after starting with compose
    volumes:
      - ./database.yml:/root/.msf4/database.yml:ro
      - ~/:/home/user1:ro
    
